services:
  nci-signal-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: danielzhu04/nci-signal-app:0.1.0
    platform: linux/amd64
    pull_policy: if_not_present
    ports:
    - 3000:3000
    x-kubernetes:
      annotations:
        maayanlab.cloud/ingress: ${PROD_NEXT_PUBLIC_URL}
    environment:
    - DATABASE_URL=${PROD_DATABASE_URL:-postgres://postgres:${POSTGRES_PASSWORD}@nci-signal-postgres:5432/postgres}
    - ADMIN_PASSWORD
    - ADMIN_SESSION_SECRET
    - OPENAI_API_KEY
    - RCLONE_CONFIG_MAAYANLAB_TYPE=s3
    - RCLONE_CONFIG_MAAYANLAB_PROVIDER
    - RCLONE_CONFIG_MAAYANLAB_ACCESS_KEY_ID
    - RCLONE_CONFIG_MAAYANLAB_SECRET_ACCESS_KEY
    - RCLONE_CONFIG_MAAYANLAB_ENDPOINT
    - RCLONE_CONFIG_MAAYANLAB_ACL
    - S3_BUCKET
    - S3_REMOTE
    - S3_PREFIX
    - S3_PUBLIC_BASE
    - NCI_SCRIPT_PROMPT

  nci-signal-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: danielzhu04/nci-signal-worker:0.1.0
    platform: linux/amd64
    pull_policy: if_not_present
    environment:
    - DATABASE_URL=${PROD_DATABASE_URL:-postgres://postgres:${POSTGRES_PASSWORD}@nci-signal-postgres:5432/postgres}
    - OPENAI_API_KEY
    - RCLONE_CONFIG_MAAYANLAB_TYPE=s3
    - RCLONE_CONFIG_MAAYANLAB_PROVIDER
    - RCLONE_CONFIG_MAAYANLAB_ACCESS_KEY_ID
    - RCLONE_CONFIG_MAAYANLAB_SECRET_ACCESS_KEY
    - RCLONE_CONFIG_MAAYANLAB_ENDPOINT
    - RCLONE_CONFIG_MAAYANLAB_ACL
    - S3_BUCKET
    - S3_REMOTE
    - S3_PREFIX
    - S3_PUBLIC_BASE
    - NCI_SCRIPT_PROMPT

  nci-signal-postgres:
    image: postgres:17
    pull_policy: missing
    restart: unless-stopped
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - 5432:5432
    volumes:
    - nci-signal-postgres-data:/var/lib/postgresql/data

volumes:
  nci-signal-postgres-data:
    x-kubernetes:
      size: 10Gi
      class: ceph-block-no-replicas

x-kubernetes:
  context: danielzhu04@sshkube
  name: nci-signal
  namespace: danielzhu04
